project_id = "wbguuipoggeamyzrfvbv"

[functions.session-start]
verify_jwt = false

[functions.query-start]
verify_jwt = false

[functions.query-end]
verify_jwt = false

[functions.log-click]
verify_jwt = false

[functions.log-scroll]
verify_jwt = false

[functions.session-end]
verify_jwt = false

[functions.query]
verify_jwt = false

[functions.log_click]
verify_jwt = false

[functions.secure-google-search]
verify_jwt = false

[functions.submit-background-survey]
verify_jwt = false

[functions.submit-post-task-survey]
verify_jwt = false

[functions.log-consent-event]
verify_jwt = false

[functions.submit-task-instruction]
verify_jwt = false

[functions.log-scroll-event]
verify_jwt = false
