project_id = "wbguuipoggeamyzrfvbv"

[functions.query]
verify_jwt = false

[functions.log_click]
verify_jwt = false

[functions.secure-google-search]
verify_jwt = false

[functions.submit-background-survey]
verify_jwt = false

[functions.submit-post-task-survey]
verify_jwt = false

[functions.log-consent-event]
verify_jwt = false